### ISSUE TITLE
current_version not bumped in config when on a network mapped drive

### ISSUE THREAD

**Issue by tuomastik** [callowayproject/bump-my-version#253]
* bump-my-version version: 0.27.0
* Python version: 3.11.4
* Operating System: Windows 10

### Description

* **Trying to get done**
  * Bump version by running `bump-my-version bump minor` in a Git repository that is located on a <b>network mapped drive in Windows 10</b>. It does not matter if bumping major/minor/patch.
  
* **What happened**
  * The command did not produce errors and the version string was correctly bumped in every file listed in the config (`.bumpversion.toml`), <b>but the `current_version` was not bumped in `.bumpversion.toml`.</b>
  
* **Finding the cause**
  * When running `bump-my-version bump minor -vvv`, one of the outputted lines showed `"Configuration file is outside of the repo. Not going to change."`. That message stems from [update_config_file()](https://github.com/callowayproject/bump-my-version/blob/1984ca34e25abf75124654c0ec061a8e9c87625d/bumpversion/config/files.py#L134). It lead me to run `git rev-parse --show-toplevel` to check my Git repository's root directory, which pointed to a different path than `pwd` due to my Git repository being located on a **network mapped drive**.

* **Workaround**
  ```bash
  cd $(git rev-parse --show-toplevel)
  bump-my-version bump minor
  ```

**Comment by coordt** [comment]
I understand what you are seeing and why it happens. bump-my-version does not change configuration files that it _detects_ are outside the repo because some people host the configuration in a central place.

It seems the [method of detection](https://github.com/callowayproject/bump-my-version/blob/0a9506b2e78cbbba71add129ae3dbdb0707140ce/bumpversion/scm.py#L53) should be improved.

I don't have the ability to re-create your scenario to test out different methods. Can you offer some ideas to determine if the configuration is within the git repo? I'm obviously just doing some basic path checking. Is there a better way?

**Comment by dornech** [comment]
From my previous experience with python-semantic-release I wonder if this is caused by the issue that Windows paths are represented a) in the classic way with a drive letter or b) as UNC Path. To translate classic to UNC Representation somewhere a .resolve() could be missing.

**Comment by dornech** [comment]
I can confirm the error and the root cause. generate-changlog accesses the file via the Path with a drive letter. `git rev-parse --show-toplevel` shows the UNC representation of the same path.

**Comment by dornech** [comment]
try to change line 131 in bumpversion/config/files.py
old:
`config_path = Path(config_file)`
new:
`config_path = Path(config_file).resolve()`

**Comment by tuomastik** [comment]
> try to change line 131 in bumpversion/config/files.py old: `config_path = Path(config_file)` new: `config_path = Path(config_file).resolve()`

I confirm this fixes the issue.
